#!/bin/sh

use_apt=$(grep debian /etc/os-release > /dev/null; echo $?)
use_xbps=$(grep void /etc/os-release > /dev/null; echo $?)

if [ $use_apt -eq 0 ]; then
    echo "apt detected..."
elif [ $use_xbps -eq 0 ]; then
    echo "xbps detected..."
fi

if [ ! -d ~/.srcconfig ]; then
    mkdir -p ~/.srcconfig
fi

if [ ! -d ~/.srcconfig/dwm-vido ]; then
    git clone git@gitlab.com:files-and-configs/dwm-vido.git ~/.srcconfig
fi

cd ~/.srcconfig/dwm-vido
sudo make install && make clean
